serviceName: &serviceName faas-runtime-service

port: 8080

baseURI: /serverless-runtime

fnPrefix: /fn

fnDir: /tmp/faas

log:
  name: *serviceName
  level: debug

mysql:
  database: xxx
  host: localhost
  port: 3306
  user: xxx
  password: xxx

fnExitTime: 10000

fnActiveTime: 86400000 # 24*60*60*1000

checkActivityInterval: 3600000